name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    name: Cypress run

    # Chạy tests song song với matrix strategy
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]  # Sử dụng 2 instance song song

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Cài đặt phiên bản Node.js

      - name: Install dependencies
        run: npm install  # Cài đặt các phụ thuộc

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          wait-on: ''
          start: ''
          record: true  # Ghi lại kết quả vào Cypress Cloud
          parallel: true  # Chạy test song song
        env:
          CYPRESS_baseUrl: 'https://www.automationexercise.com/'
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title || github.event.head_commit.message }}
          COMMIT_INFO_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
